### ISSUE TITLE
Core dump parsing try catch

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#1558]
```
#!/usr/bin/env qore
%new-style

try {
} catch (Exception e) {
    printf("%N", e);
}

```

```
qore test-coredump.q 
qore: ../include/qore/intern/VarRefNode.h:307: virtual const QoreTypeInfo* VarRefDeclNode::getTypeInfo() const: Assertion `!parseTypeInfo' failed.
Neúspěšně ukončen (SIGABRT) (core dumped [obraz paměti uložen])

```
```

(gdb) bt
#0  0xb7fdcc31 in __kernel_vsyscall ()
#1  0xb71b0876 in raise () from /usr/lib/libc.so.6
#2  0xb71b2027 in abort () from /usr/lib/libc.so.6
#3  0xb71a91e7 in __assert_fail_base () from /usr/lib/libc.so.6
#4  0xb71a926b in __assert_fail () from /usr/lib/libc.so.6
#5  0xb7b12fba in VarRefDeclNode::getTypeInfo (this=0x821d4e0) at ../include/qore/intern/VarRefNode.h:307
#6  0xb7b053e9 in yyparse (yyscanner=0x8219358) at parser.ypp:2067
#7  0xb7c12f84 in qore_program_private::parse (this=0x8194b38, fp=0x8219190, name=0x8066320 "test-coredump.q", xsink=0xbfffeb20, 
    wS=0xbfffeb24, wm=22500) at ../include/qore/intern/qore_program_private.h:923
#8  0xb7c13516 in qore_program_private::parseFile (this=0x8194b38, filename=0x8066320 "test-coredump.q", xsink=0xbfffeb20, 
    wS=0xbfffeb24, wm=22500) at ../include/qore/intern/qore_program_private.h:1002
#9  0xb7c0c2d8 in QoreProgram::parseFile (this=0x8194b28, filename=0x8066320 "test-coredump.q", xsink=0xbfffeb20, wS=0xbfffeb24, 
    wm=22500, only_first_except=false) at QoreProgram.cpp:925
#10 0x08051ee1 in qore_main_intern (argc=2, argv=0xbfffec64, other_po=0) at command-line.cpp:956
#11 0x0804ff3a in main (argc=2, argv=0xbfffec64) at qore-main.cpp:36
```

```


qore -V
QORE for Linux i386 (32-bit build), Copyright (C) 2003 - 2016 David Nichols
version 0.8.13 (builtin features: sql, threads, DGC, debug)
  git hash: f84bf7def75c434d4cefe8675fbc58acffc7fc07
  module API: 0.20 (0.19, 0.18, 0.17, 0.16, 0.15, 0.14, 0.13, 0.12, 0.11, 0.10, 0.9, 0.8, 0.7, 0.6, 0.5)
  build host: Linux hypo 4.4.6-301.fc23.i686+PAE #1 SMP Wed Mar 30 17:57:13 UTC 2016 i686 i686 i386 GNU/Linux
  C++ compiler: g++ -std=c++11
  CFLAGS: -DHAVE_UNIX_CONFIG_H -D_QORE_LIB_INTERN -DMODULE_DIR="/usr/local/lib/qore-modules" -DMODULE_VER_DIR="/usr/local/lib/qore-modules/0.8.13" -DUSER_MODULE_DIR="/usr/local/share/qore-modules" -DUSER_MODULE_VER_DIR="/usr/local/share/qore-modules/0.8.13" -g -g -m32 -fno-strict-aliasing -D_THREAD_SAFE -pthread -Wall -lm
  LDFLAGS: -lmpfr -lz -lpcre -lbz2 -lssl -lcrypto -pthread -g -lm
  MPFR: runtime: 3.1.3 built with: 3.1.3 (3.1.3)
use -B to show build options
```

**Comment by davidnich** [comment]
only crashes with debug builds
