### ISSUE TITLE
Qore coredumps when run with debug options -d 5 or -t

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#1559]
```
qore -d 5
.......
2017-01-13 07:33:32.982044: TID 1: qore_class_private::qore_class_private() this: 0x94f2678 creating '<number>' ID:93 cls: 0x94f2668 pub: 0 sys: 0
2017-01-13 07:33:32.982297: TID 1: qore_class_private::qore_class_private() this: 0x94f4150 creating '<callref>' ID:94 cls: 0x94f4140 pub: 0 sys: 0
2017-01-13 07:33:32.982409: TID 1: qore_class_private::qore_class_private() this: 0x94f4b10 creating '<closure>' ID:95 cls: 0x94f4b00 pub: 0 sys: 0
2017-01-13 07:33:32.982542: TID 1: qore_program_private_base::qore_program_private_base() this: 0x94f50e8 pgm: 0x94f50d8 po: 0
Neoprávněný přístup do paměti (SIGSEGV) (core dumped [obraz paměti uložen])

```
```

(gdb) bt
#0  0xb7cc4151 in qore_program_private::currentTZIntern (pgm=...) at ../include/qore/intern/qore_program_private.h:1638
#1  0xb7cbe9b9 in currentTZ () at thread.cpp:1156
#2  0xb7b603af in qore_date_private::qore_date_private (this=0x8195508, r=false)
    at ../include/qore/intern/qore_date_private.h:1165
#3  0xb7c4ad17 in DateTime::DateTime (this=0xbfffe3b0, r=false) at DateTime.cpp:41
#4  0xb7ba0519 in get_timestamp (str=...) at support.cpp:73
#5  0xb7ba0605 in print_debug (level=5, 
    fmt=0xb7e243a8 "qore_class_private::qore_class_private() this: %p creating copy of '%s' ID:%d cls: %p old: %p sys: %d\n")
    at support.cpp:94
#6  0xb7bbe08a in qore_class_private::qore_class_private (this=0x8195990, old=..., n_cls=0x8195488) at QoreClass.cpp:590
#7  0xb7bc91f0 in QoreClass::QoreClass (this=0x8195488, old=...) at QoreClass.cpp:2971
#8  0xb7cb6a3b in QoreClassList::QoreClassList (this=0x8195868, old=..., po=0, ns=0x8195850) at QoreClassList.cpp:99
#9  0xb7c0eb0d in qore_ns_private::qore_ns_private (this=0x8195850, old=..., po=0)
    at ../include/qore/intern/QoreNamespaceIntern.h:151
#10 0xb7c2b3e2 in qore_ns_private::newNamespace (old=..., po=0) at ../include/qore/intern/QoreNamespaceIntern.h:183
#11 0xb7c22b84 in QoreNamespace::copy (this=0x8094b50, po=0) at QoreNamespace.cpp:558
#12 0xb7c22c7f in QoreNamespaceList::QoreNamespaceList (this=0x8195650, old=..., po=0, parent=...) at QoreNamespace.cpp:569
#13 0xb7c0eba3 in qore_ns_private::qore_ns_private (this=0x81955c0, old=..., po=0)
    at ../include/qore/intern/QoreNamespaceIntern.h:151
#14 0xb7c10003 in qore_root_ns_private::qore_root_ns_private (this=0x81955c0, old=..., po=0)
    at ../include/qore/intern/QoreNamespaceIntern.h:1511
#15 0xb7c10419 in qore_root_ns_private::copy (this=0x8094cb0, po=0) at ../include/qore/intern/QoreNamespaceIntern.h:1533
#16 0xb7c1076e in qore_root_ns_private::copy (rns=..., po=0) at ../include/qore/intern/QoreNamespaceIntern.h:1615
#17 0xb7c08f10 in qore_program_private_base::newProgram (this=0x8195198) at QoreProgram.cpp:228
#18 0xb7c11666 in qore_program_private_base::qore_program_private_base (this=0x8195198, n_pgm=0x8195188, n_parse_options=0, 
    p_pgm=0x0) at ../include/qore/intern/qore_program_private.h:450
#19 0xb7c11bfe in qore_program_private::qore_program_private (this=0x8195198, n_pgm=0x8195188, n_parse_options=0)
    at ../include/qore/intern/qore_program_private.h:521
#20 0xb7c0b722 in QoreProgram::QoreProgram (this=0x8195188, po=0) at QoreProgram.cpp:710
#21 0xb7c20b3a in QoreProgramHelper::QoreProgramHelper (this=0xbfffeb28, parse_options=0, xs=...) at QoreProgramHelper.cpp:40
#22 0x08051ac0 in qore_main_intern (argc=3, argv=0xbfffec74, other_po=0) at command-line.cpp:891
#23 0x0804ff3a in main (argc=3, argv=0xbfffec74) at qore-main.cpp:36

```

```
qore -t
2017-01-13 07:40:32.256196: TID 1: FunctionList::add() entered
2017-01-13 07:40:32.256226: TID 1: FunctionList::add() exited
2017-01-13 07:40:32.256260: TID 1: FunctionList::add() entered
2017-01-13 07:40:32.256288: TID 1: FunctionList::add() exited
2017-01-13 07:40:32.256323: TID 1: FunctionList::add() entered
2017-01-13 07:40:32.256340: TID 1: FunctionList::add() exited

Program received signal SIGSEGV, Segmentation fault.
0xb7cc4151 in qore_program_private::currentTZIntern (pgm=...) at ../include/qore/intern/qore_program_private.h:1638
1638	      return pgm.priv->TZ;

```
```
(gdb) bt
#0  0xb7cc4151 in qore_program_private::currentTZIntern (pgm=...) at ../include/qore/intern/qore_program_private.h:1638
#1  0xb7cbe9b9 in currentTZ () at thread.cpp:1156
#2  0xb7b603af in qore_date_private::qore_date_private (this=0x81957a0, r=false)
    at ../include/qore/intern/qore_date_private.h:1165
#3  0xb7c4ad17 in DateTime::DateTime (this=0xbfffe3d0, r=false) at DateTime.cpp:41
#4  0xb7ba0519 in get_timestamp (str=...) at support.cpp:73
#5  0xb7ba0756 in trace_function (code=1, 
    funcname=0xb7e24360 "qore_class_private::qore_class_private(const qore_class_private& old)") at support.cpp:110
#6  0xb7bbe005 in qore_class_private::qore_class_private (this=0x81954a8, old=..., n_cls=0x8195498) at QoreClass.cpp:589
#7  0xb7bc91f0 in QoreClass::QoreClass (this=0x8195498, old=...) at QoreClass.cpp:2971
#8  0xb7cb6a3b in QoreClassList::QoreClassList (this=0x8195370, old=..., po=0, ns=0x8195358) at QoreClassList.cpp:99
#9  0xb7c0eb0d in qore_ns_private::qore_ns_private (this=0x8195358, old=..., po=0)
    at ../include/qore/intern/QoreNamespaceIntern.h:151
#10 0xb7c2b3e2 in qore_ns_private::newNamespace (old=..., po=0) at ../include/qore/intern/QoreNamespaceIntern.h:183
#11 0xb7c22b84 in QoreNamespace::copy (this=0x8094e80, po=0) at QoreNamespace.cpp:558
#12 0xb7c22c7f in QoreNamespaceList::QoreNamespaceList (this=0x8195158, old=..., po=0, parent=...) at QoreNamespace.cpp:569
#13 0xb7c0eba3 in qore_ns_private::qore_ns_private (this=0x81950c8, old=..., po=0)
    at ../include/qore/intern/QoreNamespaceIntern.h:151
#14 0xb7c10003 in qore_root_ns_private::qore_root_ns_private (this=0x81950c8, old=..., po=0)
    at ../include/qore/intern/QoreNamespaceIntern.h:1511
#15 0xb7c10419 in qore_root_ns_private::copy (this=0x8094b80, po=0) at ../include/qore/intern/QoreNamespaceIntern.h:1533
#16 0xb7c1076e in qore_root_ns_private::copy (rns=..., po=0) at ../include/qore/intern/QoreNamespaceIntern.h:1615
#17 0xb7c08f10 in qore_program_private_base::newProgram (this=0x8194d88) at QoreProgram.cpp:228
#18 0xb7c11666 in qore_program_private_base::qore_program_private_base (this=0x8194d88, n_pgm=0x8194d78, n_parse_options=0, 
    p_pgm=0x0) at ../include/qore/intern/qore_program_private.h:450
#19 0xb7c11bfe in qore_program_private::qore_program_private (this=0x8194d88, n_pgm=0x8194d78, n_parse_options=0)
    at ../include/qore/intern/qore_program_private.h:521
#20 0xb7c0b722 in QoreProgram::QoreProgram (this=0x8194d78, po=0) at QoreProgram.cpp:710
#21 0xb7c20b3a in QoreProgramHelper::QoreProgramHelper (this=0xbfffeb28, parse_options=0, xs=...) at QoreProgramHelper.cpp:40
#22 0x08051ac0 in qore_main_intern (argc=2, argv=0xbfffec74, other_po=0) at command-line.cpp:891
#23 0x0804ff3a in main (argc=2, argv=0xbfffec74) at qore-main.cpp:36

```
seems pgm.priv is NULL

```
(gdb) l
1633	   DLLLOCAL static void addStatement(QoreProgram& pgm, AbstractStatement* s) {
1634	      pgm.priv->addStatement(s);
1635	   }
1636	
1637	   DLLLOCAL static const AbstractQoreZoneInfo* currentTZIntern(QoreProgram& pgm) {
1638	      return pgm.priv->TZ;
1639	   }
1640	
1641	   DLLLOCAL static int lockParsing(QoreProgram& pgm, ExceptionSink* xsink) {
1642	      return pgm.priv->lockParsing(xsink);
(gdb) p pgm
$1 = (QoreProgram &) @0x8194d78: {<AbstractPrivateData> = {<QoreReferenceCounter> = {references = 1}, 
    _vptr.AbstractPrivateData = 0xb7fae724 <vtable for QoreProgram+8>}, priv = 0x0}
(gdb) p pgm.priv
$2 = (qore_program_private *) 0x0

```

**Comment by tmandys** [comment]
Quick fix below (I think qore treies logging too early when QoreProgram is not yet initialized) but I think QORE_TRACE (and probably printd(5)) should use raw C function to get timestamp. Using Qore stuffhas too much overhead, i.e. slow:

```
diff --git a/include/qore/QoreProgram.h b/include/qore/QoreProgram.h
index 31dd145..6d23f7e 100644
--- a/include/qore/QoreProgram.h
+++ b/include/qore/QoreProgram.h
@@ -639,6 +639,7 @@ public:
    DLLLOCAL QoreListNode* getVarList();
    DLLLOCAL void parseSetIncludePath(const char* path);
    DLLLOCAL const char* parseGetIncludePath() const;
+   DLLLOCAL bool isInitialized() const {return priv != 0;}
 
    /* for run-time module loading; the parse lock must be grabbed
       before loading new modules - note this should only be assigned
diff --git a/lib/thread.cpp b/lib/thread.cpp
index 46f70f4..7666cdb 100644
--- a/lib/thread.cpp
+++ b/lib/thread.cpp
@@ -1152,7 +1152,7 @@ const AbstractQoreZoneInfo* currentTZ() {
    if (td->tpd) {
       if (td->tlpd && td->tlpd->tz_set)
          return td->tlpd->tz;
-      if (td->current_pgm)
+      if (td->current_pgm && td->current_pgm->isInitialized())
          return qore_program_private::currentTZIntern(*(td->current_pgm));
    }
    return QTZM.getLocalZoneInfo();

```

**Comment by tmandys** [comment]
Still keep coredumping when used with high memory requirements  (SalesForce.qtest). The same place but priv pointer is a garbage, maybe memory overflow. I saw difference with some smaller file in gdb (passed) vs. not gdb (coredump). So I implemented raw tick logs. Now at least seems trace is working

```
index 738e195..7cb42f4 100644
--- a/lib/support.cpp
+++ b/lib/support.cpp
@@ -47,6 +47,8 @@ extern bool threads_initialized;
 static QoreThreadLock debug_output_lock;
 #endif
 
+#define QORE_QUICK_TIMESTAMP_LOG
+
 int printe(const char *fmt, ...) {
    va_list args;
    QoreString buf;
@@ -64,6 +66,20 @@ int printe(const char *fmt, ...) {
    return 0;
 }
 
+#ifdef QORE_QUICK_TIMESTAMP_LOG
+static void get_timestamp(int &secs, int &us) {
+   static int64 startSecs;
+   static bool initFlag = false;
+   int64 secs64 = q_epoch_us(us);
+   if (initFlag) {
+      secs = secs64-startSecs;
+   } else {
+      secs = 0;
+      startSecs = secs64;
+      initFlag = true;
+   }
+}
+#else
 static void get_timestamp(QoreString &str) {
    if (!(threads_initialized && is_valid_qore_thread()))
       return;
@@ -74,6 +90,7 @@ static void get_timestamp(QoreString &str) {
    now.setDate(currentTZ(), secs, us);
    now.format(str, "YYYY-MM-DD HH:mm:SS.xx");
 }
+#endif
 
 int print_debug(int level, const char *fmt, ...) {
    if (level > debug)
@@ -90,14 +107,23 @@ int print_debug(int level, const char *fmt, ...) {
         break;
    }
 
+   int tid = (threads_initialized && is_valid_qore_thread()) ? gettid() : -1;
+#ifdef QORE_QUICK_TIMESTAMP_LOG
+   int secs, us;
+   get_timestamp(secs, us);
+#ifdef QORE_SERIALIZE_DEBUGGING_OUTPUT
+   AutoLocker al(debug_output_lock);
+#endif
+   fprintf(stderr, "%d.%d: TID %d: %s", secs, us, tid, buf.getBuffer());
+#else
    QoreString ts;
    get_timestamp(ts);
 
 #ifdef QORE_SERIALIZE_DEBUGGING_OUTPUT
    AutoLocker al(debug_output_lock);
 #endif
-   int tid = (threads_initialized && is_valid_qore_thread()) ? gettid() : -1;
    fprintf(stderr, "%s: TID %d: %s", ts.getBuffer(), tid, buf.getBuffer());
+#endif
    fflush(stderr);
    return 0;
 }
@@ -106,12 +132,22 @@ void trace_function(int code, const char *funcname) {
    if (!qore_trace)
       return;
 
+#ifdef QORE_QUICK_TIMESTAMP_LOG
+   int secs, us;
+   get_timestamp(secs, us);
+   if (code == TRACE_IN)
+      printe("%d.%d: TID %d: %s entered\n", secs, us, threads_initialized  && is_valid_qore_thread() ? gettid() : 0, funcname);
+   else
+      printe("%d.%d: TID %d: %s exited\n", secs, us, threads_initialized  && is_valid_qore_thread() ? gettid() : 0, funcname);
+#else
+
    QoreString ts;
    get_timestamp(ts);
    if (code == TRACE_IN)
       printe("%s: TID %d: %s entered\n", ts.getBuffer(), threads_initialized  && is_valid_qore_thread() ? gettid() : 0, funcname);
    else
       printe("%s: TID %d: %s exited\n", ts.getBuffer(), threads_initialized  && is_valid_qore_thread() ? gettid() : 0, funcname);
+#endif
 }

 char *remove_trailing_newlines(char *str) {
```

**Comment by tmandys** [comment]
```
valgrind --track-origins=yes qore -t

==30032== Use of uninitialised value of size 8
==30032==    at 0x529E5D8: qore_program_private::currentTZIntern(QoreProgram&) (qore_program_private.h:1638)
==30032==    by 0x529919C: currentTZ() (thread.cpp:1156)
==30032==    by 0x51375E0: qore_date_private::qore_date_private(bool) (qore_date_private.h:1165)
==30032==    by 0x5223DF0: DateTime::DateTime(bool) (DateTime.cpp:41)
==30032==    by 0x51775CF: get_timestamp(QoreString&) (support.cpp:73)
==30032==    by 0x5177898: trace_function(int, char const*) (support.cpp:110)
==30032==    by 0x5195949: qore_class_private::qore_class_private(qore_class_private const&, QoreClass*) (QoreClass.cpp:589)
==30032==    by 0x51A13B1: QoreClass::QoreClass(QoreClass const&) (QoreClass.cpp:2968)
==30032==    by 0x529165D: QoreClassList::QoreClassList(QoreClassList const&, long long, qore_ns_private*) (QoreClassList.cpp:99)
==30032==    by 0x51E6CB6: qore_ns_private::qore_ns_private(qore_ns_private const&, long long) (QoreNamespaceIntern.h:151)
==30032==    by 0x5202C84: qore_ns_private::newNamespace(qore_ns_private const&, long long) (QoreNamespaceIntern.h:183)
==30032==    by 0x51F9EC3: QoreNamespace::copy(long long) const (QoreNamespace.cpp:558)
==30032==  Uninitialised value was created by a heap allocation
==30032==    at 0x4C2C20C: operator new(unsigned long) (vg_replace_malloc.c:334)
==30032==    by 0x51F7E96: QoreProgramHelper::QoreProgramHelper(long long, ExceptionSink&) (QoreProgramHelper.cpp:40)
==30032==    by 0x409C7A: qore_main_intern(int, char**, int) (command-line.cpp:891)
==30032==    by 0x4080F8: main (qore-main.cpp:36)
==30032==
==30032== Invalid read of size 8
==30032==    at 0x529E5D8: qore_program_private::currentTZIntern(QoreProgram&) (qore_program_private.h:1638)
==30032==    by 0x529919C: currentTZ() (thread.cpp:1156)
==30032==    by 0x51375E0: qore_date_private::qore_date_private(bool) (qore_date_private.h:1165)
==30032==    by 0x5223DF0: DateTime::DateTime(bool) (DateTime.cpp:41)
==30032==    by 0x51775CF: get_timestamp(QoreString&) (support.cpp:73)
==30032==    by 0x5177898: trace_function(int, char const*) (support.cpp:110)
==30032==    by 0x5195949: qore_class_private::qore_class_private(qore_class_private const&, QoreClass*) (QoreClass.cpp:589)
==30032==    by 0x51A13B1: QoreClass::QoreClass(QoreClass const&) (QoreClass.cpp:2968)
==30032==    by 0x529165D: QoreClassList::QoreClassList(QoreClassList const&, long long, qore_ns_private*) (QoreClassList.cpp:99)
==30032==    by 0x51E6CB6: qore_ns_private::qore_ns_private(qore_ns_private const&, long long) (QoreNamespaceIntern.h:151)
==30032==    by 0x5202C84: qore_ns_private::newNamespace(qore_ns_private const&, long long) (QoreNamespaceIntern.h:183)
==30032==    by 0x51F9EC3: QoreNamespace::copy(long long) const (QoreNamespace.cpp:558)
==30032==  Address 0x350 is not stack'd, malloc'd or (recently) free'd
==30032==
==30032==
==30032== Process terminating with default action of signal 11 (SIGSEGV)
==30032==  Access not within mapped region at address 0x350
==30032==    at 0x529E5D8: qore_program_private::currentTZIntern(QoreProgram&) (qore_program_private.h:1638)
==30032==    by 0x529919C: currentTZ() (thread.cpp:1156)
==30032==    by 0x51375E0: qore_date_private::qore_date_private(bool) (qore_date_private.h:1165)
==30032==    by 0x5223DF0: DateTime::DateTime(bool) (DateTime.cpp:41)
==30032==    by 0x51775CF: get_timestamp(QoreString&) (support.cpp:73)
==30032==    by 0x5177898: trace_function(int, char const*) (support.cpp:110)
==30032==    by 0x5195949: qore_class_private::qore_class_private(qore_class_private const&, QoreClass*) (QoreClass.cpp:589)
==30032==    by 0x51A13B1: QoreClass::QoreClass(QoreClass const&) (QoreClass.cpp:2968)
==30032==    by 0x529165D: QoreClassList::QoreClassList(QoreClassList const&, long long, qore_ns_private*) (QoreClassList.cpp:99)
==30032==    by 0x51E6CB6: qore_ns_private::qore_ns_private(qore_ns_private const&, long long) (QoreNamespaceIntern.h:151)
==30032==    by 0x5202C84: qore_ns_private::newNamespace(qore_ns_private const&, long long) (QoreNamespaceIntern.h:183)
==30032==    by 0x51F9EC3: QoreNamespace::copy(long long) const (QoreNamespace.cpp:558)
==30032==  If you believe this happened as a result of a stack
==30032==  overflow in your program's main thread (unlikely but
==30032==  possible), you can try to increase the size of the
==30032==  main thread stack using the --main-stacksize= flag.
==30032==  The main thread stack size used in this run was 8388608.
==30032==
==30032== HEAP SUMMARY:
==30032==     in use at exit: 1,752,719 bytes in 28,187 blocks
==30032==   total heap usage: 41,775 allocs, 13,588 frees, 2,933,205 bytes allocated
==30032==
==30032== LEAK SUMMARY:
==30032==    definitely lost: 0 bytes in 0 blocks
==30032==    indirectly lost: 0 bytes in 0 blocks
==30032==      possibly lost: 336 bytes in 1 blocks
==30032==    still reachable: 1,752,383 bytes in 28,186 blocks
==30032==                       of which reachable via heuristic:
==30032==                         newarray           : 120 bytes in 5 blocks
==30032==         suppressed: 0 bytes in 0 blocks
==30032== Rerun with --leak-check=full to see details of leaked memory
==30032==
==30032== For counts of detected and suppressed errors, rerun with: -v
==30032== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
Killed

```

**Comment by davidnich** [comment]
@tmandys ok I see, it's the same issue; https://github.com/qorelanguage/qore/pull/1561 should fix it, the pull request has been assigned to you (I had a bug in it yesterday)
