### ISSUE TITLE
hang in program.qtest for unknown reason

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#2169]
only reproducible in jenkins builds (w/ qore debugging enabled) - no clue why

I have not been able to reproduce the hang when executing the same code by hand as the jenkins user with the same configuration

**Comment by omusil24** [comment]
Happened a lot of times in the past... I couldn't reproduce it either.

**Comment by davidnich** [comment]
can only be reproduced while jenkins is running a qore build on the xbox build server - Ivy Bridge i7-3770T 2.5GHz - CentOS 7

If jenkins is not running a Qore build, the deadlock cannot be reproduced on the command-line.  If jenkins is running a Qore build, then the bug may happen in Jenkins and also can be reproduced on the command-line, but only while Jenkins is running and only using the same binaries that Jenkins is using.

The source code is correct - it must be either a glibc bug (`futex()` bug for example - some issue with condition variables and pthread mutexes with `PTHREAD_MUTEX_RECURSIVE`), a hardware issue (CPU microcode maybe?) or a related memory bug in libqore causing this (not likely but possible).

**Comment by omusil24** [comment]
Stacktraces for all the threads:
```
(gdb) info thread
  Id   Target Id         Frame 
  3    Thread 0x7ff7e5b7a700 (LWP 30862) "qore" 0x00007ff7e7588371 in sigwait () from /lib64/libpthread.so.0
  2    Thread 0x7ff7e4bb6700 (LWP 30866) "qore" 0x00007ff7e7584945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
* 1    Thread 0x7ff7e9bc1940 (LWP 30860) "qore" 0x00007ff7e7584945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ff7e7584945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007ff7e939f849 in QoreCondition::wait (this=0x1eb25b8, m=0x1eb2590) at QoreCondition.cpp:55
#2  0x00007ff7e94805bb in QoreCondition::wait (this=0x1eb25b8, l=0x1eb2590) at ../include/qore/QoreCondition.h:100
#3  0x00007ff7e95040d6 in qore_counter_private::waitForZero (this=0x1eb2590, xsink=0x7ffe34a36fe0, timeout_ms=0) at QoreCounter.cpp:93
#4  0x00007ff7e93ab8ae in QoreCounter::waitForZero (this=0x7ff7e99a2638 <thread_counter>, xsink=0x7ffe34a36fe0, timeout_ms=0) at QoreCounter.cpp:141
#5  0x00007ff7e9338393 in QoreProgramHelper::~QoreProgramHelper (this=0x7ffe34a36fd0, __in_chrg=<optimized out>) at QoreProgramHelper.cpp:48
#6  0x00000000004092ed in qore_main_intern (argc=2, argv=0x7ffe34a37178, other_po=0) at command-line.cpp:998
#7  0x0000000000409400 in main (argc=2, argv=0x7ffe34a37178) at qore-main.cpp:36
(gdb) thread 2
[Switching to thread 2 (Thread 0x7ff7e4bb6700 (LWP 30866))]
#0  0x00007ff7e7584945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ff7e7584945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007ff7e939f849 in QoreCondition::wait (this=0x270d520, m=0x270d5c8) at QoreCondition.cpp:55
#2  0x00007ff7e94805bb in QoreCondition::wait (this=0x270d520, l=0x270d5c8) at ../include/qore/QoreCondition.h:100
#3  0x00007ff7e948063b in QoreCondition::wait (this=0x270d520, l=...) at ../include/qore/QoreCondition.h:131
#4  0x00007ff7e94d071c in qore_program_private::waitForAllThreadsToTerminateIntern (this=0x270d4e0) at ../include/qore/intern/qore_program_private.h:553
#5  0x00007ff7e9332d5e in qore_program_private::waitForTerminationAndClear (this=0x270d4e0, xsink=0x7ff7e4bb58d0) at QoreProgram.cpp:344
#6  0x00007ff7e93362ad in QoreProgram::waitForTerminationAndDeref (this=0x26c4de0, xsink=0x7ff7e4bb58d0) at QoreProgram.cpp:1016
#7  0x00007ff7e941f552 in Program_destructor (self=0x26c4ee0, p=0x26c4de0, xsink=0x7ff7e4bb58d0) at QC_Program.qpp:700
#8  0x00007ff7e9318db7 in BuiltinDestructorVariant::evalDestructor (this=0x1f82050, thisclass=..., self=0x26c4ee0, xsink=0x7ff7e4bb58d0) at QoreClass.cpp:4671
#9  0x00007ff7e9319b91 in DestructorMethodFunction::evalDestructor (this=0x1f82110, thisclass=..., self=0x26c4ee0, xsink=0x7ff7e4bb58d0) at QoreClass.cpp:4810
#10 0x00007ff7e94b2369 in qore_method_private::evalDestructor (this=0x1f81ca0, self=0x26c4ee0, xsink=0x7ff7e4bb58d0) at ../include/qore/intern/QoreClassIntern.h:3247
#11 0x00007ff7e9310198 in qore_class_private::execDestructor (this=0x1f802e0, self=0x26c4ee0, xsink=0x6e75660000003a3a) at QoreClass.cpp:3213
#12 0x00007ff7e93100ac in QoreClass::execDestructor (this=0x1f802c0, self=0x26c4ee0, xsink=0x6e75660000003a3a) at QoreClass.cpp:3191
#13 0x00007ff7e94b423a in qore_object_private::doDeleteIntern (this=0x26f72c0, xsink=0x6e75660000003a3a) at ../include/qore/intern/QoreObjectIntern.h:461
#14 0x00007ff7e9368978 in qore_object_private::customDeref (this=0x26f72c0, real=true, xsink=0x6e75660000003a3a) at QoreObject.cpp:749
#15 0x00007ff7e9368a9d in qore_object_private::endCall (this=0x26f72c0, xsink=0x6e75660000003a3a) at QoreObject.cpp:765
#16 0x00007ff7e9386d1e in CodeContextHelperBase::~CodeContextHelperBase (this=0x7ff7e4bb5c40, __in_chrg=<optimized out>) at thread.cpp:1453
#17 0x00007ff7e949dfda in CodeContextHelper::~CodeContextHelper (this=0x7ff7e4bb5c40, __in_chrg=<optimized out>) at ../include/qore/intern/qore_thread_intern.h:812
#18 0x00007ff7e93880d9 in (anonymous namespace)::op_background_thread (x=0x2681c80) at thread.cpp:2045
#19 0x00007ff7e7580e25 in start_thread () from /lib64/libpthread.so.0
#20 0x00007ff7e72ae34d in clone () from /lib64/libc.so.6
(gdb) thread 3
[Switching to thread 3 (Thread 0x7ff7e5b7a700 (LWP 30862))]
#0  0x00007ff7e7588371 in sigwait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ff7e7588371 in sigwait () from /lib64/libpthread.so.0
#1  0x00007ff7e92f4b67 in QoreSignalManager::signal_handler_thread (this=0x7ff7e99a1860 <QSM>) at QoreSignal.cpp:308
#2  0x00007ff7e92f4f5a in sig_thread (x=0x0) at QoreSignal.cpp:392
#3  0x00007ff7e7580e25 in start_thread () from /lib64/libpthread.so.0
#4  0x00007ff7e72ae34d in clone () from /lib64/libc.so.6
```

**Comment by davidnich** [comment]
has not happened in years - assuming fixed
