### ISSUE TITLE
Finding function variant with space in argument coredumps

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#2601]
Reproducible in debugger (where is also bug wrongly stripping space in argument), issue in C++ 

```
qdbg> statement assign 1 "func(int,int)"
cmd "program/6/breakpoint/1/statement/assign" server-side error: RUNTIME-OVERLOAD-ERROR: no variant matching 'func(func(int, int)) can be found; the following variants are defined:
   func(string s, int i)
qdbg> statement assign 1 "func(int, int)"
qore: parser.ypp:1124: static const QoreTypeInfo* ParserTypeStruct::getRuntimeType(const char*): Assertion `str[0]' failed.
Aborted (core dumped [obraz paměti uložen])

resolveStatement: hash: (2 members)
  function : "main"
  args : list: (2 elements)
    [0]="int"
    [1]=""
pgm.findFunctionStatementId(value.function, value.args);


#0  0x00007fe11511069b in raise () from /usr/lib64/libc.so.6
#1  0x00007fe1151123b1 in abort () from /usr/lib64/libc.so.6
#2  0x00007fe11510892a in __assert_fail_base () from /usr/lib64/libc.so.6
#3  0x00007fe1151089a2 in __assert_fail () from /usr/lib64/libc.so.6
#4  0x00007fe11755f803 in ParserTypeStruct::getRuntimeType (str=0x2cbc090 "") at parser.ypp:1124
#5  0x00007fe1172fc007 in qore_get_type_from_string (str=0x2cbc090 "") at parser.ypp:1148
#6  0x00007fe1173bd725 in qore_root_ns_private::runtimeFindCall (this=0x2bb0540, name=0x2ca53a0 "func", params=0x2ca5d00, 
    xsink=0x7fff3c650090) at QoreNamespace.cpp:1777
#7  0x00007fe1173b18af in qore_program_private::runtimeFindCall (this=0x2bafd80, name=0x2ca53a0 "func", params=0x2ca5d00, 
    xsink=0x7fff3c650090) at QoreProgram.cpp:1098
#8  0x00007fe1173b4c2c in QoreProgram::runtimeFindCall (this=0x2b9a300, name=0x2ca53a0 "func", params=0x2ca5d00, xsink=0x7fff3c650090)
    at QoreProgram.cpp:1947
#9  0x00007fe1173b4a50 in QoreProgram::findFunctionStatement (this=0x2b9a300, functionName=0x2ca53a0 "func", params=0x2ca5d00, 
    xsink=0x7fff3c650090) at QoreProgram.cpp:1896
#10 0x00007fe11749e230 in ProgramControl_findFunctionStatementId_VsNl (self=0x7fe1080151f0, p=0x2b9a300, args=0x2cbe980, rtflags=0, 
    xsink=0x7fff3c650090) at QC_ProgramControl.qpp:352
#11 0x00007fe11752d6d3 in BuiltinNormalMethodValueVariant::evalImpl (this=0x2278600, self=0x7fe1080151f0, private_data=0x2b9a300, 
    args=0x2cbe980, rtflags=0, xsink=0x7fff3c650090) at ../include/qore/intern/QoreClassIntern.h:495
#12 0x00007fe1173e71b5 in qore_object_private::evalBuiltinMethodWithPrivateData (this=0x7fe1080152b0, method=..., meth=0x2278600, 
    args=0x2cbe980, rtflags=0, xsink=0x7fff3c650090) at QoreObject.cpp:589
#13 0x00007fe11753864e in qore_object_private::evalBuiltinMethodWithPrivateData (obj=..., method=..., meth=0x2278600, args=0x2cbe980, 
    rtflags=0, xsink=0x7fff3c650090) at ../include/qore/intern/QoreObjectIntern.h:733
#14 0x00007fe1173941bb in BuiltinNormalMethodVariantBase::evalMethod (this=0x2278600, self=0x7fe1080151f0, ceh=..., xsink=0x7fff3c650090)
    at QoreClass.cpp:4899
#15 0x00007fe117393d69 in NormalMethodFunction::evalMethod (this=0x22787a0, xsink=0x7fff3c650090, variant=0x2278600, self=0x7fe1080151f0, 
    args=0x2b33b00, cctx=0x0) at QoreClass.cpp:4864
#16 0x00007fe1175359c5 in qore_method_private::eval (this=0x22788d0, xsink=0x7fff3c650090, self=0x7fe1080151f0, args=0x2b33b00, cctx=0x0)
    at ../include/qore/intern/QoreClassIntern.h:3295
#17 0x00007fe117535c71 in qore_method_private::eval (m=..., xsink=0x7fff3c650090, self=0x7fe1080151f0, args=0x2b33b00, cctx=0x0)
    at ../include/qore/intern/QoreClassIntern.h:3329
#18 0x00007fe11734d280 in AbstractMethodCallNode::exec (this=0x2b33d50, o=0x7fe1080151f0, c_str=0x2b338a0 "findFunctionStatementId", 
    xsink=0x7fff3c650090) at FunctionCallNode.cpp:61
#19 0x00007fe117526afd in MethodCallNode::exec (this=0x2b33d50, o=0x7fe1080151f0, xsink=0x7fff3c650090)
    at ../include/qore/intern/FunctionCallNode.h:311
#20 0x00007fe117435677 in QoreDotEvalOperatorNode::evalValueImpl (this=0x2b33960, needs_deref=@0x7fff3c64a6a8: true, xsink=0x7fff3c650090)
    at QoreDotEvalOperatorNode.cpp:59
#21 0x00007fe11751a7b3 in ParseNode::evalValue (this=0x2b33960, needs_deref=@0x7fff3c64a6a8: true, xsink=0x7fff3c650090)
    at ../include/qore/intern/ParseNode.h:135
#22 0x00007fe11745529d in ValueEvalRefHolder::evalIntern (this=0x7fff3c64a690, exp=0x2b33960) at QoreValue.cpp:548
#23 0x00007fe1174551fb in ValueEvalRefHolder::ValueEvalRefHolder (this=0x7fff3c64a690, exp=0x2b33960, xs=0x7fff3c650090)
    at QoreValue.cpp:536
#24 0x00007fe11751a334 in ParseNode::evalImpl (this=0x2b33960, xsink=0x7fff3c650090) at ../include/qore/intern/ParseNode.h:77
#25 0x00007fe1173390d5 in AbstractQoreNode::eval (this=0x2b33960, xsink=0x7fff3c650090) at AbstractQoreNode.cpp:190
#26 0x00007fe11735e2c8 in ReturnStatement::execImpl (this=0x2b33dd0, return_value=..., xsink=0x7fff3c650090) at ReturnStatement.cpp:37
#27 0x00007fe11735db13 in AbstractStatement::exec (this=0x2b33dd0, return_value=..., xsink=0x7fff3c650090) at AbstractStatement.cpp:67
#28 0x00007fe11735ee57 in StatementBlock::execIntern (this=0x2b33e30, return_value=..., xsink=0x7fff3c650090) at StatementBlock.cpp:241
#29 0x00007fe11735ec33 in StatementBlock::execImpl (this=0x2b33e30, return_value=..., xsink=0x7fff3c650090) at StatementBlock.cpp:216
#30 0x00007fe11736182d in IfStatement::execImpl (this=0x2b33eb0, return_value=..., xsink=0x7fff3c650090) at IfStatement.cpp:58
#31 0x00007fe11735db13 in AbstractStatement::exec (this=0x2b33eb0, return_value=..., xsink=0x7fff3c650090) at AbstractStatement.cpp:67
#32 0x00007fe11735ee57 in StatementBlock::execIntern (this=0x2b33650, return_value=..., xsink=0x7fff3c650090) at StatementBlock.cpp:241
#33 0x00007fe11735ec33 in StatementBlock::execImpl (this=0x2b33650, return_value=..., xsink=0x7fff3c650090) at StatementBlock.cpp:216
#34 0x00007fe11735ea21 in StatementBlock::exec (this=0x2b33650, xsink=0x7fff3c650090) at StatementBlock.cpp:180
#35 0x00007fe1173598a1 in UserVariantBase::evalIntern (this=0x2b34da0, argv=..., self=0x2b983b0, xsink=0x7fff3c650090) at Function.cpp:1650
#36 0x00007fe117359b5a in UserVariantBase::eval (this=0x2b34da0, name=0x2b33110 "resolveStatement", ceh=0x7fff3c64ad50, self=0x2b983b0, 
    xsink=0x7fff3c650090, qc=0x2aef5c0) at Function.cpp:1696
#37 0x00007fe117391ef6 in UserMethodVariant::evalMethod (this=0x2b34d50, self=0x2b983b0, ceh=..., xsink=0x7fff3c650090)
    at QoreClass.cpp:4565
#38 0x00007fe117393d69 in NormalMethodFunction::evalMethod (this=0x2b83770, xsink=0x7fff3c650090, variant=0x2b34d50, self=0x2b983b0, 
    args=0x2b23f70, cctx=0x0) at QoreClass.cpp:4864
#39 0x00007fe1175359c5 in qore_method_private::eval (this=0x2b1d600, xsink=0x7fff3c650090, self=0x2b983b0, args=0x2b23f70, cctx=0x0)
    at ../include/qore/intern/QoreClassIntern.h:3295
#40 0x00007fe117535c71 in qore_method_private::eval (m=..., xsink=0x7fff3c650090, self=0x2b983b0, args=0x2b23f70, cctx=0x0)
    at ../include/qore/intern/QoreClassIntern.h:3329
#41 0x00007fe11738954b in QoreClass::evalMethod (this=0x2b88060, self=0x2b983b0, nme=0x2b23ee0 "resolveStatement", args=0x2b23f70, 
    xsink=0x7fff3c650090) at QoreClass.cpp:3099
#42 0x00007fe1173e8689 in QoreObject::evalMethodValue (this=0x2b983b0, name=0x2b23ee0 "resolveStatement", args=0x2b23f70, 
    xsink=0x7fff3c650090) at QoreObject.cpp:890
#43 0x00007fe11734d2a5 in AbstractMethodCallNode::exec (this=0x2b201d0, o=0x2b983b0, c_str=0x2b23ee0 "resolveStatement", 
    xsink=0x7fff3c650090) at FunctionCallNode.cpp:64
#44 0x00007fe11734dc69 in SelfFunctionCallNode::evalValueImpl (this=0x2b201d0, needs_deref=@0x7fff3c64b118: true, xsink=0x7fff3c650090)
    at FunctionCallNode.cpp:191
#45 0x00007fe11751a7b3 in ParseNode::evalValue (this=0x2b201d0, needs_deref=@0x7fff3c64b118: true, xsink=0x7fff3c650090)
    at ../include/qore/intern/ParseNode.h:135
#46 0x00007fe11745529d in ValueEvalRefHolder::evalIntern (this=0x7fff3c64b100, exp=0x2b201d0) at QoreValue.cpp:548
#47 0x00007fe1174551fb in ValueEvalRefHolder::ValueEvalRefHolder (this=0x7fff3c64b100, exp=0x2b201d0, xs=0x7fff3c650090)
    at QoreValue.cpp:536
#48 0x00007fe117338f11 in AbstractQoreNode::evalValue (this=0x2b201d0, xsink=0x7fff3c650090) at AbstractQoreNode.cpp:164
#49 0x00007fe1173f7abb in QoreValueListEvalOptionalRefHolder::evalIntern (this=0x7fff3c64b340, exp=0x2b238c0) at QoreValueList.cpp:934

```

**Comment by davidnich** [comment]
there is an error, but there is no crash in release builds - instead there is:
```
qdbg> statement assign 1 "func(int, int)"
cmd "program/6/breakpoint/1/statement/assign" server-side error: FIND-CALL-ERROR: call "func()" parameter 2 "" cannot be resolved to a known type
```
