### ISSUE TITLE
Strict list indexes

### ISSUE THREAD

**Issue by geckon** [qorelanguage/qore#2703]
I'd like to propose a change similar to #990 but for lists.

The following behavior can lead to bugs and I believe that attempts to access an element outside of a list should throw an exception to prevent them. It returns `NOTHING` instead though:
```
$ qore -nX '("a", "b", "c")[10]'
<NOTHING>
```

Since we probably can't break backward compatibility, it can be solved by adding a `%strict-list` parse directive (or similar) that would turn the exceptions throwing on.

It could affect list slicing too and return only items that actually exist which makes much more sense to me anyway:
```
$ qore -nX '("a", "b", "c")[2..10]'
list: (9 elements)
  [0]="c"
  [1]=<NOTHING>
  [2]=<NOTHING>
  [3]=<NOTHING>
  [4]=<NOTHING>
  [5]=<NOTHING>
  [6]=<NOTHING>
  [7]=<NOTHING>
  [8]=<NOTHING>
```

Comparison with e.g. python:
```
>>> ["a", "b", "c"][10]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range

>>> ["a", "b", "c"][2:10]
['c']
```

**Comment by martin-zemek** [comment]
see the discussion in
https://github.com/qorelanguage/qore/issues/1781

**Comment by davidnich** [comment]
@martin-zemek @geckon the issues in #1781 relate to lvalue assignments with specific indices, specifically:
```
list l = (0,1,2,3,4);
(*int i0, *int i1, *int i2) = l[0,7,2];
```

if the rvalue in the second line would return `(0,2)`, then things would break.  If we had something like what's proposed here, then we would get a runtime exception and nothing would break.

Also note that this is related to the often-requested "strict hash keys" behavior where Qore would throw an exception when an invalid hash key is referenced instead of returning `NOTHING`.

**Comment by geckon** [comment]
@davidnich I know about issue #990 for hashes, maybe these two could be combined and the parse directive could be something like `%strict-containers` or something like that.

BTW, runtime exception is exactly what Python does in cases like you described. 

```
>>> a, b = ["a", "b", "c", "d"][0:3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack
```

I think it would be a good solution for qore (with the proposed directive) as well.

**Comment by davidnich** [comment]
@geckon sounds reasonable to me - BTW do you know how Python behaves when a non-existent hash key (dictionary key?) is referenced?

**Comment by geckon** [comment]
@davidnich Throws an exception as well:

```
>>> d = dict()
>>> d["unknown"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'unknown'
```

**Comment by davidnich** [comment]
@geckon ok thanks.  Note that there is also #488 which could be a catchall for such issues - basically it will enforce much stronger checks and semantics on all types including hashes and lists - it is the main issue that needs to be implemented to enable an efficient Qore compiler to be written BTW (llvm-qore)
