### ISSUE TITLE
autotools "make html" is coredumping 

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#3013]
When building _make html_ then particular command coredumps. Corresponding cmake's _make docs_ passes:

```
QORE_MODULE_DIR=./qlib ./qore doxygen/qdx -M=qlib/RestSchemaValidator.qm:doxygen/qlib/RestSchemaValidator.qm -tHttpServerUtil.tag=../../HttpServerUtil/html doxygen/qlib/Doxyfile.tmpl doxygen/qlib/Doxyfile.RestSchemaValidator
make[1]: *** [Makefile:2690: doxygen/qlib/Doxyfile.RestSchemaValidator] Segmentation fault (obraz paměti uložen)
make[1]: Opouští se adresář „/home/tma/work/qore/qore“
make: *** [Makefile:2028: html-recursive] Chyba 1

```

_this_ pointer is wrong

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/tma/work/qore/qore/.libs/lt-qore doxygen/qdx -M=qlib/RestSchemaValidator.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fcb5697830b in qore_ns_private::getPath (this=0x7c, str=..., anchored=false) at ../include/qore/intern/QoreNamespaceIntern.h:121
121	        const qore_ns_private* w = parent;
[Current thread is 1 (Thread 0x7fcb570fb840 (LWP 25882))]
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.6-24.fc27.x86_64 glibc-2.26-16.fc27.x86_64 gmp-6.1.2-6.fc27.x86_64 libgcc-7.2.1-2.fc27.x86_64 libstdc++-7.2.1-2.fc27.x86_64 libxml2-2.9.5-2.fc27.x86_64 libyaml-0.1.7-4.fc27.x86_64 mpfr-3.1.5-5.fc27.x86_64 openssl-libs-1.1.0g-1.fc27.x86_64 pcre-8.41-3.fc27.x86_64 xz-libs-5.2.3-4.fc27.x86_64 zlib-1.2.11-4.fc27.x86_64
(gdb) bt
#0  0x00007fcb5697830b in qore_ns_private::getPath (this=0x7c, str="", anchored=false) at ../include/qore/intern/QoreNamespaceIntern.h:121
#1  0x00007fcb567d19ab in QoreNamespace::addSystemClass (this=0x7fcb4fbccf18 <XNS>, oc=0x176e7f0) at QoreNamespace.cpp:253
#2  0x00007fcb4f9b2067 in xml_module_init () at xml-module.cpp:125
#3  0x00007fcb567906ff in QoreModuleManager::loadBinaryModuleFromPath (this=0x7fcb56eb0fe0 <QMM>, xsink=..., 
    path=0x1755c10 "/usr/local/lib64/qore-modules/xml-api-0.22.qmod", feature=0x15d70a0 "xml", pgm=0x159e310, reexport=false)
    at ModuleManager.cpp:1298
#4  0x00007fcb5678dad1 in QoreModuleManager::loadModuleIntern (this=0x7fcb56eb0fe0 <QMM>, xsink=..., name=0x15d70a0 "xml", pgm=0x159e310, 
    reexport=false, op=MOD_OP_GE, version=0x7fff5fc154c0, src=0x0, mpgm=0x0, load_opt=0) at ModuleManager.cpp:805
#5  0x00007fcb5678e47f in QoreModuleManager::parseLoadModule (this=0x7fcb56eb0fe0 <QMM>, xsink=..., name=0x15d6fb0 "xml >= 1.3", 
    pgm=0x159e310, reexport=false) at ModuleManager.cpp:910
#6  0x00007fcb56734732 in yylex (yylval_param=0x7fff5fc18e40, yylloc_param=0x7fff5fc18e20, yyscanner=0x15d2c60) at scanner.lpp:951
#7  0x00007fcb56716860 in yyparse (yyscanner=0x15d2c60) at parser.cpp:6745
#8  0x00007fcb5698501c in qore_program_private::parse (this=0x159e330, fp=0x13fd880, 
    name=0x15d0700 "/home/tma/work/qore/qore/qlib/RestSchemaValidator.qm", xsink=0x7fff5fc1b8c0, wS=0x7fff5fc1b8c0, wm=87008)
    at ../include/qore/intern/qore_program_private.h:1081
#9  0x00007fcb569856af in qore_program_private::parseFile (this=0x159e330, 
    filename=0x15d0700 "/home/tma/work/qore/qore/qlib/RestSchemaValidator.qm", xsink=0x7fff5fc1b8c0, wS=0x7fff5fc1b8c0, wm=87008)
    at ../include/qore/intern/qore_program_private.h:1167
#10 0x00007fcb567cd419 in QoreProgram::parseFile (this=0x159e310, 
    filename=0x15d0700 "/home/tma/work/qore/qore/qlib/RestSchemaValidator.qm", xsink=0x7fff5fc1b8c0, wS=0x7fff5fc1b8c0, wm=87008, 
    only_first_except=false) at QoreProgram.cpp:1579
#11 0x00007fcb5678f3b9 in QoreModuleManager::loadUserModuleFromPath (this=0x7fcb56eb0fe0 <QMM>, xsink=..., 
    path=0x1586c4a "qlib/RestSchemaValidator.qm", feature=0x1587a30 "RestSchemaValidator", tpgm=0x13fe920, reexport=false, pgm=0x159e310, 
    path_pgm=0x0, load_opt=0) at ModuleManager.cpp:1066
#12 0x00007fcb5678d805 in QoreModuleManager::loadModuleIntern (this=0x7fcb56eb0fe0 <QMM>, xsink=..., 
    name=0x1586c4a "qlib/RestSchemaValidator.qm", pgm=0x13fe920, reexport=false, op=MOD_OP_NONE, version=0x0, src=0x0, mpgm=0x0, 
    load_opt=0) at ModuleManager.cpp:766
#13 0x00007fcb5678e511 in QoreModuleManager::parseLoadModule (this=0x7fcb56eb0fe0 <QMM>, xsink=..., 
    name=0x1586c4a "qlib/RestSchemaValidator.qm", pgm=0x13fe920, reexport=false) at ModuleManager.cpp:915
#14 0x00007fcb56735187 in yylex (yylval_param=0x7fff5fc1f0d0, yylloc_param=0x7fff5fc1f0b0, yyscanner=0x159e1f0) at scanner.lpp:1012
#15 0x00007fcb56716860 in yyparse (yyscanner=0x159e1f0) at parser.cpp:6745
#16 0x00007fcb5698496f in qore_program_private::internParsePending (this=0x1571f40, xsink=0x7fff5fc22d70, 
    code=0x159d680 "%requires qlib/RestSchemaValidator.qm\nhash sub get() { return get_module_hash().'RestSchemaValidator'; }\n", 
    label=0x151a5d0 "mod", orig_src=0x0, offset=0) at ../include/qore/intern/qore_program_private.h:934
#17 0x00007fcb5698544e in qore_program_private::parse (this=0x1571f40, 
    code=0x159d680 "%requires qlib/RestSchemaValidator.qm\nhash sub get() { return get_module_hash().'RestSchemaValidator'; }\n", 
    label=0x151a5d0 "mod", xsink=0x7fff5fc22d70, wS=0x0, wm=0, orig_src=0x0, offset=0)
    at ../include/qore/intern/qore_program_private.h:1138
#18 0x00007fcb569852a6 in qore_program_private::parse (this=0x1571f40, str=0x159d3c0, lstr=0x151a590, xsink=0x7fff5fc22d70, wS=0x0, wm=0,
```

**Comment by davidnich** [comment]
this is related to the ABI change in Qore - all modules need to be rebuilt - please rebuild your binary modules and try again
