### ISSUE TITLE
crash in stream handling

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#3189]
```
Core was generated by `/export/home/dnichols/src/Qorus/current/bin/qwf 0.1 tcp://192.168.20.7:49903 19'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007ff010e4753f in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7ff010c94840 (LWP 13231))]
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.6-28.fc29.x86_64 glibc-2.28-23.fc29.x86_64 gmp-6.1.2-8.fc29.x86_64 java-1.8.0-openjdk-1.8.0.191.b12-11.fc29.x86_64 java-1.8.0-openjdk-headless-1.8.0.191.b12-11.fc29.x86_64 libX11-1.6.7-1.fc29.x86_64 libXau-1.0.8-14.fc29.x86_64 libXext-1.3.3-10.fc29.x86_64 libXi-1.7.9-8.fc29.x86_64 libXrender-0.9.10-8.fc29.x86_64 libXtst-1.2.3-8.fc29.x86_64 libaio-0.3.111-3.fc29.x86_64 libatomic-8.2.1-5.fc29.x86_64 libgcc-8.2.1-5.fc29.x86_64 libnsl-2.28-23.fc29.x86_64 libssh2-1.8.0-8.fc29.x86_64 libstdc++-8.2.1-5.fc29.x86_64 libuuid-2.32.1-1.fc29.x86_64 libxcb-1.13.1-1.fc29.x86_64 libxml2-2.9.8-4.fc29.x86_64 libyaml-0.2.1-2.fc29.x86_64 mpfr-3.1.6-2.fc29.x86_64 openssl-libs-1.1.1-3.fc29.x86_64 pcre-8.42-5.fc29.x86_64 sssd-client-2.0.0-4.fc29.x86_64 xz-libs-5.2.4-3.fc29.x86_64 zlib-1.2.11-14.fc29.x86_64
(gdb) bt
#0  0x00007ff010e4753f in raise () from /lib64/libc.so.6
#1  0x00007ff010e31895 in abort () from /lib64/libc.so.6
#2  0x00007ff010e8a927 in __libc_message () from /lib64/libc.so.6
#3  0x00007ff010e9125c in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ff010e914b4 in malloc_consolidate () from /lib64/libc.so.6
#5  0x00007ff010e92dea in _int_free () from /lib64/libc.so.6
#6  0x00007ff010e953fe in _int_realloc () from /lib64/libc.so.6
#7  0x00007ff010e9667b in realloc () from /lib64/libc.so.6
#8  0x00007ff011a1ba1d in BinaryNode::append (this=0x7052610, nptr=0x6d05bf0, size=27) at ../lib/BinaryNode.cpp:100
#9  0x00007ff011dd768b in BinaryOutputStream::write (this=0x69cff00, ptr=0x6d05bf0, count=27, xsink=0x7ffcff311788) at ../include/qore/intern/BinaryOutputStream.h:63
#10 0x00007ff011d00dec in StreamWriter::write (this=0x6a28be0, ptr=0x6d05bf0, count=27, xsink=0x7ffcff311788) at ../include/qore/intern/StreamWriter.h:63
#11 0x00007ff011bebca4 in QoreSerializable::serializeHashToStream (h=..., writer=..., xsink=0x7ffcff311788) at ../lib/QoreSerializable.cpp:946
#12 0x00007ff011beb9ee in QoreSerializable::serializeValueToStream (val=..., writer=..., xsink=0x7ffcff311788) at ../lib/QoreSerializable.cpp:875
#13 0x00007ff011bebe70 in QoreSerializable::serializeHashToStream (h=..., writer=..., xsink=0x7ffcff311788) at ../lib/QoreSerializable.cpp:969
#14 0x00007ff011beb9ee in QoreSerializable::serializeValueToStream (val=..., writer=..., xsink=0x7ffcff311788) at ../lib/QoreSerializable.cpp:875
#15 0x00007ff011beb923 in QoreSerializable::serializeValueToStream (val=..., stream=..., xsink=0x7ffcff311788) at ../lib/QoreSerializable.cpp:869
#16 0x00007ff011beb67c in QoreSerializable::serializeToStream (h=..., stream=..., xsink=0x7ffcff311788) at ../lib/QoreSerializable.cpp:846
#17 0x00007ff011beb5ac in QoreSerializable::serialize (val=..., stream=..., xsink=0x7ffcff311788) at ../lib/QoreSerializable.cpp:830
#18 0x00007ff011c53ce7 in static_Serializable_serialize_VA (args=0x69d2500, rtflags=0, xsink=0x7ffcff311788) at QC_Serializable.qpp:435
#19 0x00007ff011d4a302 in BuiltinStaticMethodValueVariant::evalMethod (this=0x1785d80, self=0x0, ceh=..., xsink=0x7ffcff311788) at ../include/qore/intern/QoreClassIntern.h:508
#20 0x00007ff011a81096 in StaticMethodFunction::evalMethod (this=0x1785bc0, xsink=0x7ffcff311788, variant=0x1785d80, args=0x3647020, cctx=0x0) at ../lib/QoreClass.cpp:4673
#21 0x00007ff011c9dd82 in qore_method_private::eval (this=0x1785cc0, xsink=0x7ffcff311788, self=0x0, args=0x3647020, cctx=0x0) at ../include/qore/intern/QoreClassIntern.h:3307
#22 0x00007ff011c84aff in qore_method_private::eval (m=..., xsink=0x7ffcff311788, self=0x0, args=0x3647020, cctx=0x0) at ../include/qore/intern/QoreClassIntern.h:3347
#23 0x00007ff011a29148 in StaticMethodCallNode::evalImpl (this=0x36470e0, needs_deref=@0x7ffcff307070: true, xsink=0x7ffcff311788) at ../lib/FunctionCallNode.cpp:711
#24 0x00007ff011a05f14 in AbstractQoreNode::eval (this=0x36470e0, needs_deref=@0x7ffcff307070: true, xsink=0x7ffcff311788) at ../lib/AbstractQoreNode.cpp:173
```

**Comment by davidnich** [comment]
was an environment issue
