### ISSUE TITLE
qore can crash with socket errors when the connection is closed but operations are attempted on memory that's been deallocated

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#339]
invisible = bug in unreleased code

**Comment by davidnich** [comment]
can still crash if the ssl object is deleted while managed by a SSLSocketHelperHelper object

```
Program terminated with signal 11, Segmentation fault.
#0  0x0000003d62e0eb6d in raise () from /lib64/libpthread.so.0
(gdb) where
#0  0x0000003d62e0eb6d in raise () from /lib64/libpthread.so.0
#1  0x00002ba40b0335b6 in skgesigOSCrash () from /appl/oracle/product/client_11202/lib/libclntsh.so.11.1
#2  0x00002ba40b2d1609 in kpeDbgSignalHandler () from /appl/oracle/product/client_11202/lib/libclntsh.so.11.1
#3  0x00002ba40b0337c6 in skgesig_sigactionHandler () from /appl/oracle/product/client_11202/lib/libclntsh.so.11.1
#4  <signal handler called>
#5  deref (this=0x2ba86f202d10) at ../include/qore/intern/SSLSocketHelper.h:78
#6  SSLSocketHelperHelper::error (this=0x2ba86f202d10) at QoreSocket.cpp:264
#7  0x00002ba407963fc6 in upgradeServerToSSLIntern (this=<value optimized out>, cert=0x2ba44cde1ed0, pkey=0x2ba44cde2030, timeout_ms=30000, xsink=0x2ba86f203fe0)
    at ../include/qore/intern/qore_socket_private.h:1077
#8  QoreSocket::upgradeServerToSSL (this=<value optimized out>, cert=0x2ba44cde1ed0, pkey=0x2ba44cde2030, timeout_ms=30000, xsink=0x2ba86f203fe0) at QoreSocket.cpp:1477
#9  0x00002ba40796408a in QoreSocketObject::upgradeServerToSSL (this=0x2ba41dea9560, timeout_ms=30000, xsink=0x2ba86f203fe0) at QoreSocketObject.cpp:534
#10 0x00002ba407964113 in Socket_upgradeServerToSSL_Vt (self=<value optimized out>, s=0x2ba41dea9560, args=<value optimized out>, rtflags=<value optimized out>, xsink=0x2ba86f203fe0) at QC_Socket.qpp:2554
#11 0x00002ba407a3a7f2 in BuiltinNormalMethodValueVariant::evalImpl (this=0x3a8cfac3, self=0x397ca640, private_data=0x2ba86851dd50, args=0x3d629549f0, rtflags=416864672, xsink=0x2ba86f203fe0)
    at ../include/qore/intern/QoreClassIntern.h:507
#12 0x00002ba407911a46 in qore_object_private::evalBuiltinMethodWithPrivateData (this=0x2ba41c123460, method=..., meth=0x18df7df0, args=0x336dfda0, rtflags=0, xsink=0x2ba86f203fe0) at QoreObject.cpp:260
#13 0x00002ba407911b8e in evalBuiltinMethodWithPrivateData (this=0x18df7df0, self=0x2ba41dff7c10, ceh=..., xsink=0x2ba86f203fe0) at ../include/qore/intern/QoreObjectIntern.h:985
```
