### ISSUE TITLE
crash in QoreStringNode::parseBase64ToString() at QoreStringNode.cpp:258

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#996]
stacktrace:

```
#4  <signal handler called>
#5  QoreStringNode::parseBase64ToString (this=<optimized out>, qe=0x9f6ee90, xsink=<optimized out>) at QoreStringNode.cpp:258
#6  0x00002b7342d3bae7 in f_parse_base64_string_to_string_VsNs (args=0x2b7371a7eb80, rtflags=<optimized out>, xsink=0x2b73dbe31fe0) at ql_misc.qpp:1246
#7  0x00002b7342e3e9ec in BuiltinFunctionValueVariant::evalFunction (this=0xa0fb930, name=0xa0fbaa8 "parse_base64_string_to_string", ceh=..., xsink=0x2b73dbe31fe0) at ../include/qore/intern/BuiltinFunction.h:152
#8  0x00002b7342d508c7 in QoreFunction::evalFunction (this=<optimized out>, variant=0xa0fb930, args=<optimized out>, pgm=0x0, xsink=0x2b73dbe31fe0) at Function.cpp:1179
#9  0x00002b7342c3ab57 in FunctionCallNode::evalValueImpl (this=<optimized out>, needs_deref=<optimized out>, xsink=0x2b73724d9a50) at FunctionCallNode.cpp:288
#10 0x00002b7342c74a3c in ParseNode::evalValue (xsink=0x2b7370000030, needs_deref=@0xffffffffffffffff: <error reading variable>, this=0x2b73724d9a50) at ../include/qore/intern/ParseNode.h:129
#11 ValueEvalRefHolder::ValueEvalRefHolder (this=0x2b73dbe2d7c0, exp=0x10527e70, xs=0x2b73dbe31fe0) at QoreValue.cpp:442
...
```

to debug:
log in as build on the shared FS; 

``` Shell
cd ~/src/el5/Qorus/debug/2016-06-20-msepl-3.1.0_final
gdb
set solib-search-path ../qorus-3.1.0_final/lib:../qorus-3.1.0_final/lib/modules
set solib-absolute-prefix ../rhel5-libs-6/
file ../qorus-3.1.0_final/bin/qorus
core-file core.9787
```

**Comment by tethal** [comment]
```
qore -nX 'parse_base64_string_to_string("")'
Segmentation fault (core dumped)
```
